#!/usr/bin/with-contenv sh

# wait for services to come up
sleep 2
cp /etc/service.d/homeseer/shutdown /HomeSeer
echo "Starting HomeSeer..."
cd /HomeSeer
exec mono ./HSConsole.exe --log

!/usr/bin/execlineb -P

# TERM broadcast is ignored in order to shut down gracefully,

trap
{
  term
  {
    echo [run homeseer] TERM received
  }
  hup
  {
    echo [run homeseer] HUP received
  }
}

cd /HomeSeer
./shutdown
